# Generated by Django 6.0.4 on 2026-05-03 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0004_seed_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='phone',
        ),
    ]
